import collections,json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
d=json.loads((R/'analysis/subtask-factorization.json').read_text())
rows=[json.loads(l) for l in (R/'analysis/subtask-factorization-segments.jsonl').read_text().splitlines()]
parts=['# Single-tool decomposition and product predictions from existing trajectories\n','This offline analysis reads existing outputs without inference or training. It covers four Qwen2.5 Base scales and three seeds each: 10368 name-condition trajectories and 10368 corresponding step trajectories. Name outputs contain 48384 required call positions and 40119 emitted segments. Per model, the original test has 384 examples × three seeds and independent confirmation has 480 × three seeds. These trajectories are not all independent programs.\n',
'## Scoring and prediction\n',
'- A: the name in emitted position i equals the requested name at position i. Missing names fail; the denominator includes unfilled positions.\n- B: after an emitted valid name, the full primitive sequence matches that name and numeric transitions are correct. A wrong selected name can still have correct B if expanded correctly. Numeric checks use the actual input state, not an oracle-correct state.\n- B is unobserved for calls whose names were never emitted; these are neither successes nor failures. This survivor selection prevents direct interpretation as independent call accuracy.\n- Primary prediction: estimate pA and pB within model, seed, and length, then predict (pA×pB)^L. Use five folds grouped by complete tool sequence, fitting on four folds and predicting the held-out fold. Numeric variants and all three seeds for a sequence share a fold.\n- Sensitivity analyses multiply position-specific pA(L, i) by tool-specific pB(tool), then across calls, and separately retain products of position-specific joint success. Estimates depend on finite samples and conditioning; selecting the closest prediction cannot establish independence.\n- The primary whole-task score requires the specified operation trajectory, every number, and the final answer, rather than only the answer. All 10368 reconstructed scores match existing strict scores. Extra segments, final answers, and formatting are checked. The product model does not separately fit final termination, a limitation of its scope.\n- Minimal scoring checks cover a wrong name with correct expansion, a missing segment, within-tool truncation, and arithmetic errors.\n',
'## Original 3–5-call examples\n','| Model | Name accuracy per position | Correct expansion of emitted names | Complete name sequence correct | Simple product whole-task prediction | Actual name-condition whole task | Actual step whole task |\n|---|---:|---:|---:|---:|---:|---:|']
unit=[]
for model in ['qwen1.5b','qwen3b','qwen7b','qwen32b']:
 rs=[r for r in rows if r['family']=='main' and r['model']==model];slots=[s for r in rs for s in r['slots']];segs=[s for r in rs for s in r['segments'] if s['tool'] is not None]
 a=sum(s['A'] for s in slots)/len(slots);b=sum(s['B'] for s in segs)/len(segs);names=sum(r['name_sequence_ok'] for r in rs)/len(rs)
 z=next(r for r in d['aggregate'] if r['family']=='main' and r['model']==model and r['length']==0)
 unit.append(dict(model=model,A_correct=sum(s['A'] for s in slots),A_total=len(slots),B_correct=sum(s['B'] for s in segs),B_total=len(segs),name_sequence=names))
 parts.append('| '+model+' | '+' | '.join(f'{100*v:.2f}%' for v in [a,b,names,z['pooled_product'],z['actual'],z['flat_strict']])+' |')
parts+=['\n## 32B by length: simple and stratified products\n','| Dataset | Calls | Simple product | Position/tool-stratified product | Actual name condition | Actual step |\n|---|---:|---:|---:|---:|---:|']
for family in ['main','independent']:
 for z in d['aggregate']:
  if z['model']=='qwen32b' and z['family']==family and z['length']:
   parts.append(f'| {family} | {z["length"]} | '+' | '.join(f'{100*z[k]:.2f}%' for k in ['pooled_product','position_tool_product','actual','flat_strict'])+' |')
parts+=['\n## Interpretation\n','On the original 3–5-call examples, simple product predictions differ from actual name-condition accuracy by approximately 0.6–2.4 percentage points. This aggregate agreement quantitatively supports the proposed two-part decomposition. For 32B, complete expansion after emitted names is approximately 99.6%, complete name-sequence accuracy 74.7%, and complete execution 73.0%. Descriptively, most loss concerns name-sequence completeness/selection rather than arithmetic after generated names.\n',
'On independent 32B confirmation at 5/6/8 calls, however, the simple product substantially underpredicts: 47.35/21.01/9.54% versus 57.99/32.64/24.65% actual accuracy. Agreement on the original test therefore does not establish general independence. Position/tool stratification still underpredicts. Failures may cluster within trajectories, including the structural dependence created by missing all subsequent names after early stopping, as well as program/state difficulty and selection on unobserved B. The approximation is useful at some lengths but does not identify independent internal learning.\n',
'The more stratified product predicts 22.83/52.59/55.47/69.09% across the four scales on the original test, versus 29.77/59.72/57.90/73.00% actual accuracy. Aggregate agreement depends on probability estimation; the more favorable formula cannot be shown alone.\n',
'Nameless step outputs contain no independently observable name-selection event, so equivalent A/B events cannot be manufactured from those trajectories. Their strict whole-task scores serve as baselines; operation segments are not treated as explicit name choices.\n',
'This is not an oracle experiment: names are not corrected and unperformed executions are not supplied. Oracle interventions are needed to measure those counterfactual capabilities.\n',
'## Auditable files\n','- `src/subtask_factorization.py`: raw-file reading, hash verification, segment scoring, and program-grouped cross-prediction.\n- `analysis/subtask-factorization.json`: sources, seed/length metrics, summaries, and conditional bootstrap intervals. These resample programs with fixed prediction residuals, omit fitting uncertainty, and do not establish statistical equivalence.\n- `analysis/subtask-factorization-segments.jsonl`: all names, primitives, states, and itemized A/B scores.\n- `analysis/subtask-factorization-predictions.jsonl`: held-out predictions and outcomes per example.\n- `analysis/subtask-factorization-checks.json`: scoring-boundary checks.\n']
(R/'SUBTASK_FACTORIZATION.md').write_text('\n'.join(parts))
(R/'analysis/subtask-factorization-unit-counts.json').write_text(json.dumps(unit,indent=2))
(R/'analysis/subtask-factorization-source-hashes.json').write_text(json.dumps({name:hashlib.sha256((R/name).read_bytes()).hexdigest() for name in ['src/subtask_factorization.py','src/report_subtask_factorization.py','SUBTASK_FACTORIZATION.md']},indent=2))
print('\n'.join(parts[:9]));print(json.dumps(unit))
